import Link from "next/link";
import type { Metadata } from "next";
import { ConsultationLink, Closing, FaqList, Flow } from "@/components/site";
import { industries, plans, webProduction } from "@/lib/site-config";
export const metadata: Metadata = { alternates: { canonical: "/" } };
export default function Home() {
  return <main id="main">
    <section className="hero"><div className="container"><div className="hero-topline"><p>店舗と、小さな事業のための制作チーム</p><span aria-hidden="true">AKINAEL AI</span></div><div className="hero-grid"><div className="hero-copy"><h1><span>商いの願いを</span><span>叶える<span className="hero-ai">AI</span></span></h1><p className="hero-lead">お店のWebサイト、文章、画像、ちょっとした調査。<br className="desktop-break" />「こんなの作れたら」から、相談できます。</p><div className="actions"><ConsultationLink /><Link prefetch={false} className="text-link" href="/service/">サービス詳細を見る</Link></div><p className="caption">まず無料で試作を確認。契約は、納得してから。</p></div><aside className="request-note" aria-label="相談できることの例"><p className="eyebrow">たとえば、こんなこと。</p><p className="request-line">新しいメニューを、<br />もっと知ってもらいたい。</p><p className="request-line">ホームページを、<br />お店らしく整えたい。</p><p className="request-line">やりたいことはある。<br />でも、手が回らない。</p><Link prefetch={false} href="#service" className="note-link">相談できることを見る <span aria-hidden="true">↓</span></Link></aside></div><div className="hero-bottom"><p>話すところから、一緒に整理します。</p><p>相談 → 試作 → 確認 → 制作</p></div></div></section>
    <section className="section" id="service"><div className="container"><div className="section-heading"><div><p className="eyebrow">01 / できること</p><h2>気になっていた、<br />その仕事から。</h2></div><p>誰に頼むかを探す前に、まず相談を。<br />お店の状況に合わせて、必要なものを整理します。</p></div><div className="service-rows">{[["Webサイト", "初めてのお客様にも、お店のことが伝わるように。", "紹介ページの制作、既存サイトの修正、予約や問い合わせへの案内。"], ["文章・SNS", "伝えたいことを、お店の言葉で。", "お知らせ文、商品やサービスの紹介文、SNS投稿の案。"], ["画像・バナー", "言葉だけでは伝えにくいときに。", "告知画像やバナーなど、用途に合わせた画像制作の相談。"], ["調査・改善", "どこから直すか、一緒に考える。", "競合や集客の簡易調査、Webの導線を見直すための提案。"]].map(([title, lead, body]) => <article className="service-row" key={title}><h3>{title}</h3><div><p className="service-lead">{lead}</p><p>{body}</p></div></article>)}</div><Link prefetch={false} className="text-link more-link" href="/service/">対応範囲と進め方を詳しく見る <span aria-hidden="true">↗</span></Link></div></section>
    <section className="trial-band"><div className="container trial-inner"><div><p className="eyebrow">02 / 無料試作</p><h2>まず作ってみる。<br />続きは、見てから。</h2></div><div><p className="trial-lead">何ができるか、説明だけでは分からないから。</p><p>相談をもとに、簡易試作や提案を作ります。<br />実際に見て、方向性と必要な費用を確認してから、<br className="desktop-break" />契約するかを検討できます。</p><p className="trial-scope">無料試作に本番公開は含まれません。<br />有料の制作は、内容と料金を承認いただいた後に進めます。</p><Link prefetch={false} className="text-link" href="/pricing/">無料の範囲と料金を見る <span aria-hidden="true">↗</span></Link></div></div></section>
    <section className="section" id="flow"><div className="container split-layout"><div><p className="eyebrow">03 / 相談から完成まで</p><h2>話して、見て、<br />確かめながら。</h2><p className="side-copy">専門用語や、完成した指示書は不要です。<br />大事な判断は、ご自身で確かめてから。</p></div><Flow /></div></section>
    <section className="section section-muted" id="quality"><div className="container split-layout"><div><p className="eyebrow">04 / 大切にしていること</p><h2>作った後に、<br />確かめる時間を。</h2></div><div className="prose"><p>制作と検査を別の工程に分け、文章、表示、操作を確認します。気になる点は修正し、仕上げていきます。</p><p>公開や課金などの重要な操作は、人の承認を通してから。相談しただけで、有料作業が始まることはありません。</p><Link prefetch={false} className="text-link" href="/about/">アキナエルAIについて <span aria-hidden="true">↗</span></Link></div></div></section>
    <section className="section choice-section"><div className="container split-layout"><div><p className="eyebrow">頼み方を選ぶときに</p><h2>自分で作る。<br />相談して任せる。</h2></div><div className="prose"><p>制作ツールで自分で編集する。汎用AIで案を考え、内容を確かめながら使う。制作会社に得意分野や対応範囲を聞いて依頼する。仕事の進め方にも、いくつかの選択肢があります。</p><p>アキナエルAIでは、相談から制作・検査までをチームが進めます。お店の方には情報を伝えていただき、試作と費用を見てから、契約を検討いただきます。</p><Link prefetch={false} className="text-link" href="/service/#roles">任せる範囲と確認することを見る</Link></div></div></section><section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">05 / あなたの商いなら</p><h2>お店の数だけ、<br />相談のかたちがある。</h2></div><p>以下はご相談いただける内容の例です。<br />実在する顧客の実績ではありません。</p></div><div className="industry-list">{industries.map(item => <Link prefetch={false} href={`/industries/${item.slug}/`} key={item.slug}><span>{item.name}</span><strong>{item.request}</strong><span aria-hidden="true">↗</span></Link>)}</div><Link prefetch={false} className="text-link more-link" href="/cases/">相談例と作るものを見る <span aria-hidden="true">↗</span></Link></div></section>
    <section className="section price-intro"><div className="container split-layout"><div><p className="eyebrow">06 / 料金</p><h2>必要な範囲から、<br />選べます。</h2></div><div><div className="price-summary"><p>お試し</p><p className="large-price">0<span>円</span></p></div><p>月額プランは、{plans[1].name} {plans[1].price}円から。<br />Webサイトの正式制作・公開は{webProduction.startingPrice}円からです。</p><p className="caption">表示料金は税込です。対象範囲と外部費用は料金ページでご確認ください。</p><Link prefetch={false} href="/pricing/" className="text-link">料金と契約の考え方を見る <span aria-hidden="true">↗</span></Link></div></div></section>
    <section className="section"><div className="container split-layout"><div><p className="eyebrow">07 / よくある質問</p><h2>気になることを、<br />先に。</h2><Link prefetch={false} className="text-link more-link" href="/faq/">すべての質問を見る <span aria-hidden="true">↗</span></Link></div><FaqList limit={4} /></div></section><Closing />
  </main>;
}
