import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Closing, PageIntro, FaqList, PlanList, Flow } from "@/components/site";
import { industries, siteConfig, webProduction } from "@/lib/site-config";

const pages = {
  service: { label: "できることと進め方", title: "お店の仕事を、相談から。", lead: "Webサイト、文章、画像、調査。必要なものを一緒に整理し、制作と確認を重ねていきます。" },
  pricing: { label: "料金・契約の考え方", title: "試して、確かめて、選ぶ。", lead: "簡易試作までは無料で。続きが必要になったら、作業内容と費用を確認してから契約をご検討ください。" },
  faq: { label: "よくある質問", title: "気になることに、お答えします。", lead: "相談の始め方、無料で試せる範囲、制作や公開のこと。分からないことは、そのまま相談できます。" },
  cases: { label: "相談例と作るもの", title: "その相談は、こんな形に。", lead: "日々のお店の仕事から、Webや文章の制作へ。以下はご相談いただける内容の例で、実在する顧客の実績ではありません。" },
  about: { label: "アキナエルAIについて", title: "商いの願いを叶えるAI。", lead: "小さな店舗や地域の事業に、相談できる制作チームを。アキナエルAIは、そのためのサービスです。" },
  start: { label: "無料相談の始め方", title: "まず、お店のことを聞かせてください。", lead: "相談は、お客様専用ページから始められます。初めての方は無料登録へ。すでにご利用中の方は、そのままログインできます。" },
  legal: { label: "運営・法務情報", title: "サービスを利用する前に。", lead: "運営情報、契約条件、データの取り扱いに関するご案内です。" },
} as const;
type PageKey = keyof typeof pages;
function isPage(value: string): value is PageKey { return Object.hasOwn(pages, value); }
export function generateStaticParams() { return Object.keys(pages).map(page => ({ page })); }
export const dynamicParams = false;
export async function generateMetadata({ params }: { params: Promise<{page:string}> }): Promise<Metadata> {
  const {page} = await params; if (!isPage(page)) return {};
  const p = pages[page];
  return { title: p.label, description: p.lead, alternates: {canonical: `/${page}/`}, openGraph: {title: `${p.label}｜アキナエルAI`,description:p.lead,url:`/${page}/`}, ...(page === "legal" || page === "start" ? {robots:{index:false,follow:false}} : {}) };
}
export default async function DetailPage({ params }: { params: Promise<{page:string}> }) {
  const {page} = await params; if (!isPage(page)) notFound(); const p = pages[page];
  return <main id="main"><PageIntro {...p} /><section className="section"><div className="container">
    {page === "service" && <><div className="reading prose"><div className="content-block"><h2>頼み方が決まっていなくても。</h2><p>お店を紹介するページを作りたい。SNSのお知らせを考えたい。今のサイトを少し直したい。専門用語を使わず、気になっていることから相談できます。</p><h3>ご相談いただけること</h3><ul><li>Webサイトの制作・修正、予約や問い合わせへの案内</li><li>商品紹介やお知らせなどの文章、SNS投稿の案</li><li>告知画像、バナーなどの画像制作</li><li>集客・競合の調査、サイトの導線の見直し</li></ul><p>予約システム、EC、CMSなどの機能追加は、内容と費用を個別に確認します。</p></div><div className="content-block"><h2>お店の方にお願いすること。</h2><p>伝えたいことや、正確な営業情報、使いたい写真があればお知らせください。必要なものは、ご相談の内容に合わせて整理します。</p><p>素材を共有する際は、ご自身が利用できるものをご用意ください。公開する文章や料金などの事実確認と、仕上がりの確認をお願いします。</p></div><div className="content-block" id="flow"><h2>相談から、完成まで。</h2><Flow /></div><div className="content-block" id="roles"><h2>任せるところ、確かめるところ。</h2><table className="comparison"><tbody><tr><th scope="row">制作チーム</th><td>要望を整理し、調査・提案・制作・検査・修正を進めます。</td></tr><tr><th scope="row">お店の方</th><td>事業の情報と希望を伝え、内容や費用、成果物を確認します。</td></tr><tr><th scope="row">重要な操作</th><td>公開・課金・削除などは、人の承認を通してから実行します。</td></tr></tbody></table><p>自分で編集するツールとは、利用者が担う作業が異なります。アキナエルAIでは、操作方法を覚えるよりも、相談と確認に集中できる進め方を大切にしています。</p></div><div className="content-block"><h2>修正と、公開後の相談。</h2><p>試作や制作物を見て、直したい点をお伝えください。修正の範囲や追加費用の有無は、作業前に確認します。回数や納期を一律に約束するものではありません。</p><p>しっかり運用・発展運用では、公開後のWebやSNSの改善も継続して相談できます。</p><Link prefetch={false} className="text-link" href="/pricing/">プランと対象範囲を見る</Link></div><div className="content-block"><h2>制作物とデータの扱い。</h2><p>利用権、引き渡し範囲、データの取り扱いなど、正式な契約条件の確認が必要な事項は、契約前にご案内します。未確定の条件を推測してお約束することはありません。</p><Link prefetch={false} className="text-link" href="/legal/">運営・法務情報を見る</Link></div><h2>関連する質問</h2><FaqList limit={4} /></div></>}
    {page === "pricing" && <><h2 className="pricing-heading">必要な範囲から選べる、4つのプラン。</h2><p className="caption" style={{marginBlock:"20px 36px"}}>表示料金はすべて税込です。</p><PlanList /><div className="reading prose"><h2>無料で試せること。</h2><p>簡易相談、集客やSNS投稿の案、簡易リサーチ、Webサイトの簡易試作が対象です。本番公開、本格的なSEOの施工、継続的なSNS運用は無料試作に含まれません。</p><h2>Webサイトの正式制作・公開。</h2><p><strong>{webProduction.startingPrice}円〜（{webProduction.tax}）</strong>。標準は最大5ページ程度、スマートフォン対応、基本SEO、Google Map、問い合わせフォーム、公開作業などです。</p><p>ページの追加、予約、EC、CMSなど標準範囲を超える機能は、内容と料金を先にお見積りします。</p><h2>追加費用と外部サービス。</h2><p>Instagram広告運用は広告費の20%、最低5,500円 / 月です。広告費や独自ドメインなどの外部費用は別途ご負担いただきます。発展運用に広告費そのものは含まれません。</p><p>プラン外の作業は、内容・料金・対象範囲を先に説明し、明確な承認をいただいてから始めます。</p><div className="notice"><strong>相談だけでは、契約になりません。</strong><p>必要な作業が分かってから選べます。有料作業や公開は、確認なしに進めません。</p></div><h2>契約前に確認いただくこと。</h2><p>契約期間、解約方法、返金条件、提供時期などの正式条件は確認中です。条件が確定するまでは、このサイトから契約を受け付けません。</p><Link prefetch={false} className="text-link" href="/legal/">運営・法務情報を確認する</Link></div></>}
    {page === "faq" && <div className="reading"><FaqList /><p className="notice">個別の対応範囲は、今のサイトや作りたいものを確認してご案内します。</p><Link prefetch={false} className="text-link" href="/service/">対応範囲と進め方を見る</Link></div>}
    {page === "cases" && <><div className="example-grid">{industries.map(item => <article className="example" key={item.slug}><p className="eyebrow">相談例 / {item.name}</p><h2>{item.request}</h2><p>{item.body}</p><h3 style={{marginTop:24}}>作るもの・見直すこと</h3><ul>{item.tasks.map(task => <li key={task}>{task}</li>)}</ul><Link prefetch={false} className="text-link" href={`/industries/${item.slug}/`}>この業種の相談を詳しく見る</Link></article>)}</div><p className="notice">このページは相談内容のイメージを紹介しています。納品済みの制作実績、顧客の声、成果数値を掲載したものではありません。</p></>}
    {page === "about" && <div className="reading prose"><div className="content-block"><h2>お店の仕事が忙しいときにも。</h2><p>営業や接客の合間に、ホームページやSNSまで手が回らない。少し直したいだけなのに、頼む先を探すところで止まってしまう。</p><p>アキナエルAIは、そんな店舗や小さな事業の相談から、必要な調査・企画・制作を進めるサービスです。</p></div><div className="content-block"><h2>AIを使いこなすことを、仕事にしない。</h2><p>「こうしたい」「ここで困っている」を、普段の言葉で。AIチームが相談を整理し、制作と検査を分けて進めます。</p><p>試作を見てから契約を検討し、公開や課金は承認してから。仕組みの複雑さよりも、何ができて、何を確認するかを分かりやすく伝えます。</p></div><div className="content-block"><h2>運営情報について。</h2><p>正式な運営者情報やお問い合わせ先、規約は確認中です。確定前の会社名や住所を掲載していません。</p><Link prefetch={false} className="text-link" href="/legal/">運営・法務情報を見る</Link></div></div>}
    {page === "start" && <div className="reading"><h2>初めての方へ</h2><div className="step-card"><h2>01　相談用のアカウントを作る</h2><p>下のボタンからお客様専用ページを開き、「新規登録はこちら」を選んでください。登録後、お店の情報を入力します。</p></div><div className="step-card"><h2>02　相談したいことを書く</h2><p>案件を作成し、相談内容を送ります。今のサイトやSNS、作りたいものがあればお知らせください。内容がまとまっていなくても大丈夫です。</p></div><div className="step-card"><h2>03　試作や提案を確認する</h2><p>お客様専用ページで、やり取りと制作の進み具合を確認できます。試作を見た後に、正式な制作へ進むか検討します。</p></div><div className="start-action"><Link prefetch={false} className="button" href={siteConfig.portalUrl}>お客様専用ページへ進む <span aria-hidden="true">↗</span></Link><p className="caption" style={{marginTop:16}}>最初はログイン画面が開きます。初めての方は「新規登録はこちら」を選択してください。</p></div><p className="notice">無料試作に本番公開は含まれません。相談だけで契約や有料作業が始まることはありません。</p><p>すでに登録済みの方は、<Link prefetch={false} className="text-link" href={siteConfig.portalUrl}>ログインして相談の続きへ</Link></p><p style={{marginTop:24}}>ご利用前に<Link prefetch={false} className="text-link" href="/legal/">運営・法務情報</Link>をご確認ください。</p></div>}
    {page === "legal" && <div className="reading prose"><div className="legal-pending"><strong>正式な情報を確認中です。</strong><p>運営者情報、利用規約、プライバシーポリシー、特定商取引法に基づく表記は、販売開始前に確定する必要があります。このページは正式な規約を構成するものではありません。</p></div>{[["operator","運営者情報・お問い合わせ先","正式な運営者名、所在地、連絡先は未確定です。確定後に掲載します。"],["terms","利用規約・契約条件","契約期間、提供範囲、提供時期、解約方法、返金条件は、正式な条件の確定後に掲載します。"],["privacy","プライバシーポリシー","利用目的、保存期間、削除方法、外部サービスへの送信範囲などを、正式なポリシーで明示する必要があります。"],["commerce","特定商取引法に基づく表記","販売事業者、所在地、連絡先、支払時期、提供時期、解約条件などは、販売開始前に確認のうえ掲載します。"]].map(([id,title,body]) => <section id={id} key={id}><h2>{title}</h2><p>{body}</p></section>)}<h2>AIと人間の役割</h2><p>AIは相談の整理、調査、提案、制作、検査を支援します。公開、課金、返金、削除などの重要操作は人の承認を必要とします。</p></div>}
  </div></section>{page !== "start" && page !== "legal" && <Closing />}</main>;
}
